language: cpp

branches:
  only: 
  - master
  
before_install:
- sudo add-apt-repository "deb http://ppa.launchpad.net/djcj/vapoursynth/ubuntu trusty main" -y
- sudo add-apt-repository "deb http://ppa.launchpad.net/ubuntu-toolchain-r/test/ubuntu trusty main" -y
- sudo apt-get update -qq
- sudo apt-get install --allow-unauthenticated g++-5
- sudo mv /etc/default/rcS /etc/default/rcS.backup
  
install:
- sudo apt-get install opencl-headers ocl-icd-libopencl1 ocl-icd-opencl-dev python3-pip
- sudo apt-get install --allow-unauthenticated libvapoursynth-dev
- mkdir build && export PATH="`pwd`/build:${PATH}"
- wget https://github.com/ninja-build/ninja/releases/download/v1.7.2/ninja-linux.zip && unzip -q ninja-linux.zip -d build
- sudo pip3 install meson==0.44

script: 
- CC=g++5.4.1 meson build
- ninja -v -C build
- sudo PATH="`pwd`/build:${PATH}" ninja -v -C build install

notifications:
  email: false
